# Site settings
title: Binary Digital
email: contact@binarydigital.sg
url: https://binarydigital.sg
description: Get The Digital Edge !

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Binary Digital Pte. Ltd.

# Build settings
markdown: kramdown
permalink: pretty
